"""API schemas package.

This package contains all Pydantic schemas for the FastAPI integration layer.
"""

# Base schemas (legacy compatibility)
from app.api.schemas.base import (
    BundleDocResponse,
    BundleTimepointRole,
    CameraOcrCorrectionRequest,
    CameraOcrCorrectionResponse,
    CoderRequest,
    CoderResponse,
    CodeSuggestionSummary,
    HybridPipelineMetadata,
    JsonPatchOperation,
    KnowledgeMeta,
    MissingFieldPrompt,
    ParsedDocRequest,
    ProcessBundleRequest,
    ProcessBundleResponse,
    QARunRequest,
    QuestionsRequest,
    QuestionsResponse,
    RegistryRequest,
    RegistryResponse,
    RenderRequest,
    RenderResponse,
    ReporterSpeechTranscriptionResponse,
    SeedFromTextRequest,
    SeedFromTextResponse,
    SpeechTranscriptCleanupRequest,
    SpeechTranscriptCleanupResponse,
    UnifiedProcessRequest,
    UnifiedProcessResponse,
    VerifyRequest,
    VerifyResponse,
)

# QA pipeline schemas (new structured response)
from app.api.schemas.qa import (
    CodeEntry,
    CoderData,
    ModuleResult,
    ModuleStatus,
    QARunResponse,
    RegistryData,
    ReporterData,
)
from app.api.schemas.vault import (
    CRYPTO_VERSION_V1,
    VaultDeleteResponse,
    VaultRecordOut,
    VaultRecordUpsert,
    VaultSettingsOut,
    VaultSettingsUpsert,
)

__all__ = [
    # Base schemas
    "BundleDocResponse",
    "BundleTimepointRole",
    "CameraOcrCorrectionRequest",
    "CameraOcrCorrectionResponse",
    "CoderRequest",
    "CoderResponse",
    "CodeSuggestionSummary",
    "HybridPipelineMetadata",
    "KnowledgeMeta",
    "ParsedDocRequest",
    "ProcessBundleRequest",
    "ProcessBundleResponse",
    "MissingFieldPrompt",
    "QARunRequest",
    "QuestionsRequest",
    "QuestionsResponse",
    "RegistryRequest",
    "RegistryResponse",
    "RenderRequest",
    "RenderResponse",
    "ReporterSpeechTranscriptionResponse",
    "SeedFromTextRequest",
    "SeedFromTextResponse",
    "SpeechTranscriptCleanupRequest",
    "SpeechTranscriptCleanupResponse",
    "JsonPatchOperation",
    "UnifiedProcessRequest",
    "UnifiedProcessResponse",
    "VerifyRequest",
    "VerifyResponse",
    # QA pipeline schemas
    "CodeEntry",
    "CoderData",
    "ModuleResult",
    "ModuleStatus",
    "QARunResponse",
    "RegistryData",
    "ReporterData",
    # Vault schemas
    "CRYPTO_VERSION_V1",
    "VaultDeleteResponse",
    "VaultRecordOut",
    "VaultRecordUpsert",
    "VaultSettingsOut",
    "VaultSettingsUpsert",
]
