"""Constants for the CPT coder module."""

CPT_DESCRIPTIONS = {
    # Tracheostomy codes
    "31600": "Planned tracheostomy (age ≥ 2 years)",
    "31601": "Planned tracheostomy (age < 2 years)",
    "31603": "Emergency tracheostomy, transtracheal",
    "31605": "Emergency cricothyrotomy",
    "31610": "Tracheostomy with fenestration/skin flaps",
    "31611": "Tracheoesophageal fistula with speech prosthesis",
    "31612": "Percutaneous tracheal puncture",
    "31613": "Tracheostoma revision, simple",
    "31614": "Tracheostoma revision, complex with flap",
    "31615": "Tracheobronchoscopy via tracheostomy",
    # Bronchoscopy codes
    "31622": "Diagnostic bronchoscopy",
    "31627": "Navigational bronchoscopy (EMN)",
    "31628": "Transbronchial lung biopsy, single lobe",
    "+31632": "Additional transbronchial lung biopsy lobe",
    "31629": "Transbronchial needle aspiration, single lobe",
    "+31633": "Additional TBNA lobe",
    "31631": "Tracheal stent placement",
    "31635": "Removal of tracheal/bronchial foreign body (stent removal)",
    "31636": "Bronchial stent placement",
    "+31637": "Additional major bronchus stent",
    "31638": "Revision or reposition of tracheal/bronchial stent",
    "31652": "Linear EBUS-TBNA 1-2 stations",
    "31653": "Linear EBUS-TBNA 3+ stations",
    "+31654": "Radial EBUS for peripheral lesion",
    "31630": "Therapeutic dilation of airway",
    "31641": "Bronchoscopy with tumor destruction by ablative energy",
    "31645": "Therapeutic aspiration, initial session",
    "31646": "Therapeutic aspiration, repeat same stay",
    "31647": "BLVR initial lobe",
    "+31651": "BLVR additional lobe",
    "31634": "Chartis collateral ventilation assessment",
    "31624": "Bronchoalveolar lavage",
    "32555": "Ultrasound-guided thoracentesis",
    "99152": "Moderate sedation (first 15 min)",
    "+99153": "Moderate sedation add-on (each additional 15 min)",
}
